export { WelcomeCard } from './welcome-card'
export { QuickStatsCard } from './quick-stats-card'
export { TargetsCard } from './targets-card'
export { ViewsChartCard } from './views-chart-card'
export { MeetingsCard } from './meetings-card'
export { CongratulationsCard } from './congratulations-card'
export { Header } from './header'

// New refactored components
export { Sidebar } from './sidebar'
export { TaxEventsTimeline } from './tax-events-timeline'
export { WelcomeWidget } from './welcome-widget'
export { TaxEventsWidget } from './tax-events-widget'
export { TaxEventCard } from './tax-event-card'
export { StatsWidget } from './stats-widget'
export { ViewsChartWidget } from './views-chart-widget'
export { CongratulationsWidget } from './congratulations-widget'
export { MeetingsWidget } from './meetings-widget'
export { QuarterlyGanttChart } from './quarterly-gantt-chart'
export { GanttTimelineWidget } from './gantt-timeline-widget'